# Generated by Django 2.0.5 on 2018-06-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='revision_date',
            field=models.BigIntegerField(),
        ),
    ]
