# Generated by Django 2.0.5 on 2018-06-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180603_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.IntegerField()),
                ('champion', models.IntegerField()),
                ('season', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('role', models.CharField(max_length=200)),
                ('lane', models.CharField(max_length=200)),
                ('game_version', models.CharField(max_length=200)),
                ('win', models.BooleanField()),
                ('top', models.IntegerField(default=0)),
                ('mid', models.IntegerField(default=0)),
                ('jun', models.IntegerField(default=0)),
                ('adc', models.IntegerField(default=0)),
                ('sup', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Player')),
            ],
        ),
        migrations.AlterField(
            model_name='flexmatch',
            name='adc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flexmatch',
            name='jun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flexmatch',
            name='mid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flexmatch',
            name='sup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flexmatch',
            name='top',
            field=models.IntegerField(default=0),
        ),
    ]
